// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc1yzLERIo2W9hSc1TyGiuTwEDnt2Texg',
    appId: '1:51481951121:web:315dfc472a67b3e1513830',
    messagingSenderId: '51481951121',
    projectId: 'greviance-62533',
    authDomain: 'greviance-62533.firebaseapp.com',
    storageBucket: 'greviance-62533.firebasestorage.app',
    measurementId: 'G-NSR52NY1QD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9aAE-BzTCGfWs9eBpsdYRxbU_vo7_Xsg',
    appId: '1:51481951121:android:29f29e521ba73846513830',
    messagingSenderId: '51481951121',
    projectId: 'greviance-62533',
    storageBucket: 'greviance-62533.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6fXAQtGJTS2rMni3mlEki3QHdFqZmHf4',
    appId: '1:51481951121:ios:703a06b90d6cb3a2513830',
    messagingSenderId: '51481951121',
    projectId: 'greviance-62533',
    storageBucket: 'greviance-62533.firebasestorage.app',
    iosBundleId: 'com.example.greviance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6fXAQtGJTS2rMni3mlEki3QHdFqZmHf4',
    appId: '1:51481951121:ios:703a06b90d6cb3a2513830',
    messagingSenderId: '51481951121',
    projectId: 'greviance-62533',
    storageBucket: 'greviance-62533.firebasestorage.app',
    iosBundleId: 'com.example.greviance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc1yzLERIo2W9hSc1TyGiuTwEDnt2Texg',
    appId: '1:51481951121:web:a9b72e327c100740513830',
    messagingSenderId: '51481951121',
    projectId: 'greviance-62533',
    authDomain: 'greviance-62533.firebaseapp.com',
    storageBucket: 'greviance-62533.firebasestorage.app',
    measurementId: 'G-5R8NL3Z7E9',
  );
}
